happy = ["Today is a gift, and I embrace it with positivity.", "I begin each day with a grateful heart.", "I approach this day with joy and excitement.", "I hold the key to my own happiness.", "I am pure, positive energy.", "I feel healthy, joyful, and vibrant.", "I bring light with me wherever I go.", "I am filled with energy and excitement.",
"Limitless joy is my birthright.", "I stand in the joy I create from within.", "I am radiant, beautiful, and thriving.", "I am creative, passionate, and inspired.", "I feel joyful, energetic, and alive.", "I allow the flow of positive energy to effortlessly move through me.", "I live a creative, vibrant, passionate life."]

sad = ["Hardships often prepare ordinary people for an extraordinary destiny.", "I am thankful for my struggle because without it I wouldn’t have come across my strength.", "Never be ashamed of a scar. It means you were stronger than whatever tried to hurt you.", "Once you choose hope, anything is possible.", "Until you’re broken you don’t know what you’re made of. It gives you the ability to build yourself all over again, but stronger than ever", "Owning your story is the bravest thing you’ll ever do.", "There is a difference between giving up and knowing when you’ve had enough.",
"No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.", "Our greatest glory is not in never falling but in rising every time we fall.", "Even the darkest night will end and the sun will rise.", "You can’t start the next chapter of your life if you keep re-reading the last one.", "Every day may not be good, but there is some good in every day.", "One of the happiest moments in life is when you find the courage to let go of what you cannot change.", "Stop focusing on how stressed you are and remember how blessed you are."]  


Angry =["Anger makes you smaller, while forgiveness forces you to grow beyond what you were.", "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering.", "Do not let your anger lead to hatred, as you will hurt yourself more than you would the other.", "There's nothing wrong with anger provided you use it constructively.", "The best fighter is never angry.",
"When angry count to ten before you speak. If very angry, count to one hundred.", "Never respond to an angry person with a fiery comeback, even if he deserves it... Don't allow his anger to become your anger.", "Never do anything when you are in a temper, for you will do everything wrong.", "If you are patient in one moment of anger, you will escape a hundred days of sorrow.", "Anger is stupid, and stupidity will kill you more surely than your opponent's blade."
 "Don't waste your time in anger, regrets, worries, and grudges. Life is too short to be unhappy."]

Depressed = ["There is hope, even when your brain tells you there isn’t.", "Sometimes, life will kick you around, but sooner or later, you realize you’re not just a survivor. You’re a warrior, and you’re stronger than anything life throws your way.", "And if today all you did was hold yourself together, I’m proud of you.", "I have endured pain and loss. I have felt broken. I have known hardship, and I have felt lost and alone. But here I stand, trying to move forward, one day at a time. I will remember the lessons in my life because they are making me who I am. Stronger. A warrior.",
"On particularly rough days when I’m sure I can’t possibly endure, I like to remind myself that my track record for getting through bad days so far is 100%, and that’s pretty good.", "Sometimes you climb out of bed in the morning and you think, I’m not going to make it, but you laugh inside – remembering all the times you’ve felt that way.", "In the middle of winter I at last discovered that there was in me an invincible summer.", "It is wise to direct your anger towards problems - not people; to focus your energies on answers - not excuses."]

Anxious = ["No need to hurry. No need to sparkle. No need to be anybody but oneself.", "Stress is an ignorant state. It believes that everything is an emergency. Nothing is that important.", "There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will.", "Anxiety does not empty tomorrow of its sorrows, but only empties today of its strength.", "Anxiety is a thin stream of fear trickling through the mind. If encouraged, it cuts a channel into which all other thoughts are drained."  
"Nothing diminishes anxiety faster than action.", "Just when the caterpillar thought the world was ending, he turned into a butterfly.", "You cannot always control what goes on outside, but you can always control what goes on inside.", "Your mind will answer most questions if you learn to relax and wait for the answer.", "Anxiety is the dizziness of freedom.", "You don’t have to control your thoughts; you just have to stop letting them control you."] 


